In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/gnewsvector/GoogleNews-vectors-negative300.bin
/kaggle/input/ass4-nlp-test/negative.review
/kaggle/input/ass4-nlp-test/positive.review
/kaggle/input/sentimentanalyzer/negative.review
/kaggle/input/positivereview/positive.review
/kaggle/input/ass4-nlp-train/negative.review
/kaggle/input/ass4-nlp-train/dvdnegative.review
/kaggle/input/ass4-nlp-train/positive.review
/kaggle/input/ass4-nlp-train/dvdpositive.review


# read files and take only review_text and make shuffled on data

In [12]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')
import numpy as np

from nltk.stem import WordNetLemmatizer
from sklearn.linear_model import LogisticRegression
from bs4 import BeautifulSoup
#read data from file and get only review_test data
book_positive_reviews = BeautifulSoup(open('../input/ass4-nlp-train/positive.review').read())
book_positive_reviews = book_positive_reviews.findAll('review_text')

book_negative_reviews = BeautifulSoup(open('../input/ass4-nlp-train/negative.review').read())
book_negative_reviews = book_negative_reviews.findAll('review_text')

dvd_positive_reviews = BeautifulSoup(open('../input/ass4-nlp-train/dvdnegative.review').read())
dvd_positive_reviews = dvd_positive_reviews.findAll('review_text')

dvd_negative_reviews = BeautifulSoup(open('../input/ass4-nlp-train/dvdnegative.review').read())
dvd_negative_reviews = dvd_negative_reviews.findAll('review_text')

electronics_positive_reviews= BeautifulSoup(open('../input/positivereview/positive.review').read())
electronics_positive_reviews = electronics_positive_reviews.findAll('review_text')

electronics_negative_reviews= BeautifulSoup(open('../input/sentimentanalyzer/negative.review').read())
electronics_negative_reviews = electronics_negative_reviews.findAll('review_text')

kitchen_housewares_positive_reviews=BeautifulSoup(open('../input/ass4-nlp-test/positive.review').read())
kitchen_housewares_positive_reviews=kitchen_housewares_positive_reviews.findAll('review_text')

kitchen_housewares_negative_reviews=BeautifulSoup(open('../input/ass4-nlp-test/negative.review').read())
kitchen_housewares_negative_reviews=kitchen_housewares_negative_reviews.findAll('review_text')




#make shuffling
np.random.shuffle(book_positive_reviews)
np.random.shuffle(book_negative_reviews)

np.random.shuffle(dvd_positive_reviews)
np.random.shuffle(dvd_negative_reviews)

np.random.shuffle(electronics_positive_reviews)
np.random.shuffle(electronics_negative_reviews)


np.random.shuffle(kitchen_housewares_positive_reviews)
np.random.shuffle(kitchen_housewares_negative_reviews)




print(len(book_positive_reviews))
print(len(book_negative_reviews))
print(len(dvd_positive_reviews))
print(len(dvd_negative_reviews))
print(len(electronics_positive_reviews))
print(len(electronics_negative_reviews))




import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import bs4 as bs
import urllib.request
import re
import nltk
from nltk.stem import WordNetLemmatizer
from sklearn.linear_model import LogisticRegression
from bs4 import BeautifulSoup

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
1000
1000
1000
1000
1000
1000
[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /usr/share/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!



preprocessing for sentances then get labels from file name zero for negative sentance and one for positive sentance then put all sentances of train files in x_train0,and its labels in y_train0and put all sentances of test files in x_test0,and its labels in y_test0 then make sequance for train data and test data then make badded for them and finaly make train model

In [13]:
def preprocessing0(s):
    processed_article = re.sub('[^a-zA-Z]', ' ', s )
    processed_article = re.sub(r'\s+', ' ', processed_article)
    return processed_article
#get tokenized data
import re
book_positive = []
book_negative = []
dvd_positive = []
dvd_negative = []
electronics_positive = []
electronics_negative = []
kitchen_housewares_positive = []
kitchen_housewares_negative = []
for review in book_positive_reviews:
    tokens = preprocessing0(review.text)
    book_positive.append(tokens)
            
for review in book_negative_reviews:
    tokens = preprocessing0(review.text)
    book_negative.append(tokens)
            

            
for review in dvd_positive_reviews:
    tokens = preprocessing0(review.text)
    dvd_positive.append(tokens)
            
for review in dvd_negative_reviews:
    tokens = preprocessing0(review.text)
    dvd_negative.append(tokens)
            
for review in electronics_positive_reviews:
    tokens = preprocessing0(review.text)
    electronics_positive.append(tokens)
            
for review in electronics_negative_reviews:
    tokens = preprocessing0(review.text)
    electronics_negative.append(tokens)

for review in kitchen_housewares_positive_reviews:
    tokens = preprocessing0(review.text)
    kitchen_housewares_positive.append(tokens)
    
for review in kitchen_housewares_negative_reviews:
    tokens = preprocessing0(review.text)
    kitchen_housewares_negative.append(tokens)

In [14]:
#prepare labels for each file
def prepare_labels(file,label):
    labels=[]
    for i in range(len(file)):
        labels.append(label)
    l=np.array(labels)
    return l
book_positive_label0=prepare_labels(book_positive,1)
book_negative_label0=prepare_labels(book_negative,0)
dvd_positive_label0=prepare_labels(dvd_positive,1)
dvd_negative_label0=prepare_labels(dvd_negative,0)
electronics_positive_label0=prepare_labels(electronics_positive,1)
electronics_negative_label0=prepare_labels(electronics_negative,0)
kitchen_housewares_positive_label0=prepare_labels(kitchen_housewares_positive,1)
kitchen_housewares_negative_label0=prepare_labels(kitchen_housewares_negative,0)
train_data0=[book_positive,book_negative,dvd_positive,dvd_negative,electronics_positive,electronics_negative]
train_label0=[book_positive_label0,book_negative_label0,dvd_positive_label0,dvd_negative_label0,electronics_positive_label0,electronics_negative_label0]
test_data0=[kitchen_housewares_positive,kitchen_housewares_negative]
test_label0=[kitchen_housewares_positive_label0,kitchen_housewares_negative_label0]

In [18]:
import numpy as np
x_train0=np.concatenate(train_data0,axis=0)
print(x_train0.shape)
y_train0=np.concatenate(train_label0,axis=0)
print(y_train0.shape)
x_test0=np.concatenate(test_data0,axis=0)
print(x_test0.shape)
y_test0=np.concatenate(test_label0,axis=0)
print(y_test0.shape)
from keras.preprocessing.text import Tokenizer
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(x_train0)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs0 = t.texts_to_sequences(x_train0)
xtr=[]
for i in encoded_docs0:
    xtr.append(np.array(i))
xtrain0=np.array(xtr)
print('encoded_train:\n',xtrain0)

from keras.preprocessing.text import Tokenizer
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(x_test0)
tvocab_size = len(t.word_index) + 1
# integer encode the documents
tencoded_docs0 = t.texts_to_sequences(x_test0)
xte=[]
for i in tencoded_docs0:
    xte.append(np.array(i))
xtest0=np.array(xte)
print('encoded_test:\n',xtest0)

d=[]
for i in xtrain0:
    d.append(len(i))
    
maxsize=max(d)
from keras.preprocessing.sequence import pad_sequences
max_length = maxsize
padded_train0 = pad_sequences(xtrain0, maxlen=max_length, padding='post')
print('padded_train:\n',padded_train0)

from keras.preprocessing.sequence import pad_sequences
max_length = maxsize
padded_test0 = pad_sequences(xtest0, maxlen=max_length, padding='post')
print('padded_test:\n',padded_test0)

from sklearn.tree import DecisionTreeClassifier
clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 200,max_depth=10, min_samples_leaf=5)
# Performing training
clf_gini.fit(padded_train0,y_train0)
print("Classification rate: ",clf_gini.score(padded_test0,y_test0))
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
y_pred=clf_gini.predict(padded_test0)
print ("Accuracy : ",accuracy_score(y_test0,y_pred)*100)
print("Report : ",classification_report(y_test0, y_pred))

(6000,)
(6000,)
(2000,)
(2000,)


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:20: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


encoded_train:
 [array([   10,    57,  1075, 20816, 14714,    13,     1,   161,     5,
         1176,   943,  2860,    54,     5,     1,  2260,   778,     5,
          944, 14715,    43,     8,    11,   128,  1021,     5,   587,
          448,    15,   131,    11,    44,   886,    63,   758,     2,
          106,    14,  1283,    32,     1,   128,    65, 14715,   634,
         2703,    12, 20817, 14714,   102,    19,    22,   139,  9168,
            2,    46,   255,     4,  6785,  1650,    24,    36,  6786,
         7424,  1029,  1246, 12384,   943,     2,   107,   609,  6787,
          327,     1,    24,     8,   255,    12,  1700,     7,  2438,
           17,     4,  1111,   666,   510,     3,     1,  8099,    10,
           29,     5,   169,     1,   161,     5,  1176,   943,     8,
            1,    95,     5,     4,   374,    11,  1193,  1419,    52,
            4,  2200,  2102, 12385,     1,  6263,   478,     1,    95,
            8,   214,   121,     1,  1166,     5,     1,  220

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:33: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


encoded_test:
 [array([ 408,   10,   57, 1602,   19,   13,  118,   30,   46,   11,   57,
        2859, 1603,    7,  729,    1, 1604, 5413,  237,    8,   29,  334,
          29,  105,  178,    2,   77,  715,  169,  715,   50,    2,   21,
          24,  384,   15,    1,   87,  820,   22,   23, 5414,    4,    1,
         400,    8,    5, 4036,  603, 3319,    4,    5,   44,   78,   75,
          56,   38,   13, 1280,   10])
 array([  65,  129,   26, 1605, 1045,  934,    4,  447, 3320,   10,  342,
          54,  140,  635, 5415, 2036,  674,  472,  118,   28,    5,  215,
          56, 2037,   15,    5,  636, 4037, 4038])
 array([ 536, 5416,   89,    3,   27,    5, 2860,    4,  129,   52,    2,
         287,    1, 5417,  537,  268,  300,    4,   81,  384,   15,   32,
           1,  221,  318,    9,  300,   22,   32, 1215,  140,  769,   52,
           4,   15,  730,    4,   22,   23,   76,   29,  770,    6,   30,
        1115,    6,    1, 4039,  537, 5418,  790,  155, 3321])
 ...
 array([   2,

# in code 2 after got sequances make tokonization for its and for each word get embedded vector using pretrained model(GoogleNews-vectors) and make it as input for model and got accuracy of 58%